search/urls.py
from django.conf.urls import url

from property import views
from search.views import SearchPropertyListView

app_name = 'search'


urlpatterns =[
     url(r'^$',SearchPropertyListView.as_view(),name='search-query'),
#      url(r'^/(?P<pk>\d+)/$',ProductDetailView.as_view(),name='product-details'),
     
]

tag/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagDetailView,
        TagListView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
] 

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.db.models import Q
from django.views.generic import ListView, DetailView
from property.models import Property, City, Category
from django.db.models import Count
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from random import shuffle

# Create your views here.


class SearchPropertyListView(ListView):
    # queryset = Product.objects.all()
    template_name = "search/search_list.html"

    def  get_context_data(self, *args, **kwargs):
        context = super(SearchPropertyListView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        city = City.objects.all().annotate(num_property = Count("property")).order_by("-num_property")
        featured = list(Property.objects.filter(featured = True))
        shuffle(featured)
        property_type  = Category.objects.all()
        context['query'] = query
        context['city'] = city
        context['property_type'] = property_type
        context['featured'] = featured
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None)
        if query is not None:
            property_list = list(Property.objects.search(query))
            shuffle(property_list)
            paginator = Paginator(property_list, 10)
            page = self.request.GET.get('page')
            

            try:
                property = paginator.page(page)
            except PageNotAnInteger:
                property = paginator.page(1)
            except EmptyPage:
                property = paginator.page(paginator.num_pages)
            return property

            # return Property.objects.search(query)
        return Property.objects.featured()
        '''
        __icontains = field contains this
        __iexact = fields is exactly this
        '''

       
       

search/templates/search/snippet/search_form.html

<div class="slider-form">
    <div class="container">
       <h1 class="text-center text-white mb-5">Find Your Favorite Property</h1>
       <form action="{% url 'search:search-query' %}"  method="GET">
          <div class="row no-gutters">
             <div class="col-md-4">
                <div class="input-group">
                   <div class="input-group-addon"><i class="mdi mdi-map-marker-multiple"></i></div>
                   <input class="form-control" placeholder="Enter address, Neighborhoods" name="q"
                   value="{{ request.GET.q }}" type="text">
                </div>
             </div>
             <div class="col-md-3">
                <div class="input-group">
                   <div class="input-group-addon"><i class="mdi mdi-google-maps"></i></div>
                   <select class="form-control select2 no-radius">
                      <option value="">For Rent</option>
                      <option value="AL">For Sale</option>
                   </select>
                </div>
             </div>
             <div class="col-md-3">
                <div class="input-group">
                   <div class="input-group-addon"><i class="mdi mdi-security-home"></i></div>
                   <select class="form-control select2 no-radius">
                      <option value="">Property Type</option>
                      <option value="">House/Villa</option>
                   </select>
                </div>
             </div>
             <div class="col-md-2">  
                <button type="submit" class="btn btn-success btn-block no-radius font-weight-bold">SEARCH</button>
             </div>
          </div>
       </form>
    </div>
 </div>