property/urls.py
from django.conf.urls import url

from .views import (
        PropertyListView, 
        PropertyDetailSlugView, 
        PropertyCreateView,
        PropertyUpdateView,
        PropertyRatingView,
        UserFavoriteProperty,
        # ContactView,
        # AboutView
)
from .import views



app_name = 'property'

urlpatterns = [
    url(r'^$',PropertyListView.as_view(),name='list'),
    # url(r'^create/$',views.create_property,name='create'),
    url(r'^(?P<slug>[\w-]+)/$',PropertyDetailSlugView.as_view(),name='details'),
    url(r'^(?P<slug>[\w-]+)/edit/$',PropertyUpdateView.as_view(),name='edit'),
    url(r'^ajax/rating/$', PropertyRatingView.as_view(), name='ajax_rating'),
    url(r'^city/(?P<slug>[\w-]+)/$', views.get_city, name ="city"),
    url(r'^city/(?P<slug>[\w-]+)/(?P<neighborhood_slug>[\w-]+)/$', views.get_neighborhood, name ="neighborhood"),
]

tag/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagDetailView,
        TagListView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
] 

property/models.py
from django.db.models import Q

import random
from django.conf import settings
import os
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from real.utils import unique_slug_generator
from main.models import User
from realtor.models import Realtor






def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext



def upload_image_path(instance, filename):
    new_filename = random.randint(1, 3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "property/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )




class City(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    image        = models.ImageField(upload_to='properties/', null=True, blank=True)
    slug         = models.SlugField(blank=True,unique=True)
    
    


    def get_city_url(self):
        return reverse("property:city", kwargs={"slug": self.slug})

    def __str__(self):
        return self.slug
    
    
    def get_property(self):
        return property.objects.filter(city__title = self.title)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'


def city_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(city_pre_save_receiver, sender=City)



class CityImage(models.Model):
    city = models.ForeignKey(City, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='city/', null=True, blank=True)

    def __str__(self):
        return self.city



# neighborhood
class Neighborhood(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    image        = models.ImageField(upload_to='properties/', null=True, blank=True)
    slug         = models.SlugField(blank=True,unique=True)
    city         = models.ForeignKey(City,blank=True, default=1, max_length=300, unique=False, on_delete=models.CASCADE)
    

    def get_neighborhood_url(self):
        return reverse("property:neighborhood", kwargs={"slug": self.city,"neighborhood_slug": self.slug})

    # def class_name(self):
    #     return self.__class__.__name__

    def __str__(self):
        return self.slug
    
    
   
    
    
    def get_property(self):
        return property.objects.filter(neighborhood__title = self.title)

    class Meta:
        verbose_name = 'Neighborhood'
        verbose_name_plural = 'Neighborhoods'


def neighborhood_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(neighborhood_pre_save_receiver, sender=Neighborhood)

class NeighborhoodImage(models.Model):
    neighborhood = models.ForeignKey(Neighborhood, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='neigborhood/', null=True, blank=True)

    def __str__(self):
        return self.neighborhood

class Category(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    slug         = models.SlugField(blank=True,unique=True)

    def get_category_url(self):
        return reverse("property:category-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.slug
    
    
    def get_property(self):
        return property.objects.filter(category__title = self.title)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(category_pre_save_receiver, sender=Category)



class PropertyQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
                   Q(description__icontains=query)  # |
                   # Q(tag__title__icontains=query)
                   )
        return self.filter(lookups).distinct()


class PropertyManager(models.Manager):
    def get_queryset(self):
        return PropertyQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


STOREY = (
    ('Bungalow', 'Bungalow'),
    ('Duplex', 'Duplex'),
    ('One Storeys', 'One Storeys'),
    ('Two Storeys', 'Two Storeys'),
    ('Three Storeys', 'Three Storeys'),
    ('Four Storeys', 'Four Storeys'),
    ('Five Storeys', 'Five Storeys'),
)



FURNISHED = (
    ('yes', 'yes'),
    ('no', 'no'),
    ('somewhat', 'somewhat'),
)

NEW_PROPERTY = (
    ('yes', 'yes'),
    ('no', 'no'),
)

PARKING_SPACE = (
    ('yes', 'yes'),
    ('no', 'no'),
)

BEDROOM = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)

DURATION = (
    ('1 month', '1 month'),
    ('3 months', '3 months'),
    ('6 months', '6 months'),
    ('Year', 'Year'),
    ('2 Years', '2 Years'),
    ('3 Years', '3 Years'),
    
)

BATHROOM = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)
PURPOSE = (
    ('Residential', 'Residential'),
    ('Office', 'Office'),
    ('Business', 'Business'),
    ('Other', 'Other'),
)


class Property(models.Model):
    # realtor = models.ForeignKey(User, related_name='property')
    realtor = models.ForeignKey(Realtor, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)
    address = models.CharField(blank=True, max_length=300)
    neighborhood = models.ForeignKey(Neighborhood,blank=True,default="", max_length=300, unique=False, on_delete=models.CASCADE)
    city = models.ForeignKey(City,blank=True, default="", max_length=300, unique=False, on_delete=models.CASCADE)
    storey = models.CharField(_('storey'), blank=True, max_length=300,
                              choices=STOREY, unique=False)

    category = models.ForeignKey(Category, default="", max_length=300, unique=False, on_delete=models.CASCADE)

    bedroom = models.CharField(_('bed'), max_length=300,
                               choices=BEDROOM, unique=False)

    bathroom = models.CharField(_('bathroom'), max_length=300,
                                choices=BATHROOM, unique=False)

    description = models.TextField()

    furnished = models.CharField(_('furnished'), blank=True, max_length=300,
                                 choices=FURNISHED, unique=False)
    parking_space = models.CharField(_('parking_space'), blank=True, max_length=300,
                                     choices=PARKING_SPACE, unique=False)

    new_property = models.CharField(_('new_property'), blank=True, max_length=300,
                                    choices=NEW_PROPERTY, unique=False)

    purpose = models.CharField(_('purpose'), blank=True, max_length=300,
                               choices=PURPOSE, unique=False)
    
    duration = models.CharField(_('duration'), blank=True, max_length=300,
                               choices=DURATION, unique=False)

    square_meter = models.DecimalField(blank=True, decimal_places=2, max_digits=20, default=0.00)
    price = models.DecimalField(decimal_places=0, max_digits=20, default=0.00)
    main_image = models.ImageField(upload_to='properties/', null=True, blank=True)
    main_image_two  = models.ImageField(upload_to='properties/',  null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = PropertyManager()

    def __str__(self):
        return self.slug

    @property
    def name(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("property:details", kwargs={"slug": self.slug})
    
    def get_edit_url(self):
        return reverse("realtor:property_edit", kwargs={"pk": self.id})

    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = 'Property'


class Images(models.Model):
    property = models.ForeignKey(Property, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='properties/', null=True, blank=True)

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'
    def __str__(self):
        return self.property.title

# def create_more_images(sender, **kwarg):
#     if kwarg ['created']:
#         property_images = Images.objects.create(user=kwarg['instance'])

# post_save.connect(create_more_images, sender=Property) 


class MyProperty(models.Model):
    user = models.OneToOneField(User)
    property = models.ManyToManyField(Property, blank=True)

    def __str__(self):
        return self.property.count




property/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.forms.models import modelformset_factory
from .models import Property, Images





class PropertyForm(forms.ModelForm):

    tags = forms.CharField(label='Related tags', required=False)

    class Meta:
        model = Property

        fields = (
            'title',
            'description',
            'address',
            'neighborhood',
            'storey',
            'category',
            'city',
            'bedroom',
            'bathroom',
            'furnished',
            'parking_space',
            'address',
            'new_property',
            'purpose',
            'square_meter',
            'price',
            'main_image',
            "main_image_two",
            
        )
        widgets = {
            'description' : forms.Textarea(
                attrs= {
                    'placeholder': 'description'
                }
            ) 
        }


# class Property_ImagesForm(forms.ModelForm):
#     class Meta:
#         model = Images
#         fields = ('image',)

# # Property_ImagesFormSet = inlineformset_factory(Property,Images, form=Property_ImagesForm, extra=1)


property/templates/property/create_property_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
{% endblock %}

{% block content %}   

<section class="section-padding bg-dark inner-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1 class="mt-0 mb-3 text-white">New Property</h1>
                    <div class="breadcrumbs">
                        <p class="mb-0 text-white"><a class="text-white" href="{% url 'realtor:home' %}">My Properties</a>  /  <span class="text-success">New Property</span></p>
                    </div>
                </div>
            </div>
        </div>
</section>
        <!-- End Inner Header -->



<section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 mx-auto">
                    <div class="card padding-card">
                        <div class="card-body">
                            <h5 class="card-title mb-4">Create Property</h5>
                            <form method="post"  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <br/>
                                <br/>
                                <br/>
                                <h6 class="card-title mb-4">Add More Images</h6>
                                {{ formset|crispy }}
                                <button type="submit" class="btn btn-success btn-block">Save</button>
                            </form>
    
            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

 

{% endblock %}  

property/templates/property/favorite_list.html
{% extends "base.html" %}


{% block style %}

{% endblock style %}


{% block content %}
<h1>Library</h1>



<table class='table'>
<thead>
	<th>Property</th>
	<th>Image</th>
	<th></th>
</thead>






{% for instance in property_list %}
<tr>
<td>
<a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a>
</td>

<td>
{% if instance.image %}
	<a href='{{ instance.get_absolute_url }}'>

		<img src='{{instance.main_image.url}}"' /></a>
        <br/>
	{% endif %}

</td>


  </tr>



{% endfor %}


</table>

<li>No Favorite Property Yet.</li>


{% endblock %}

property/templates/property/property_city_detailview.html
{% extends "base.html" %}
{% load staticfiles %}
{% load classname %}

{% block style %}
    <link href='{% static "css/property_list.css" %}' rel="stylesheet">
{% endblock %}




   {% block content %}

    <!-- Main Slider With Form -->
    <section class="osahan-slider">
        <div id="osahanslider" class="carousel slide" data-ride="carousel">
            
            <div class="carousel-inner" role="listbox">
                {% if city_name %}
                
                    <div class="carousel-item active" 
                        style="background-image: {% if city_name.image %}url('{{ city_name.image.url }}') {% else %} url({% static 'images/city_view.jpg' %}){% endif %}">      
                        <div class="overlay"></div>
                    </div>
                 
                {% endif %}
               
            </div>
            
        </div>
        
        {% include 'search/snippet/search_form.html' %}
    </section>
         <!-- End Main Slider With Form -->


         
    <!-- END: header -->

  {% if city_property%}


      <!-- Properties List -->
    <section class="section-padding">
          <div class="container">
            <div class="row">
              <div class="col-lg-3 col-md-3">
      
                <div class="card">
      
                  <div class="card-body">
                    <h5 class="card-title mb-3">Property Type</h5>
      
                    <ul class="sidebar-card-list">
                      {% if property_type %}
                        {% for type in property_type %}
                          <li><a href="#"><i class="mdi mdi-chevron-right"></i> For {{ type.title }} <span class="sidebar-badge"></span></a></li>
                          <!-- <li><a href="#"><i class="mdi mdi-chevron-right"></i> For Sale <span class="sidebar-badge">1200</span></a></li> -->
                        {% endfor %}
                      {% endif %}
                    </ul>
      
      
                  </div>
                </div>
      
      
                <div class="card">
      
                  <div class="card-body">
                    {% if city_name %}
                     
                        <h6 class="card-title mb-3">Neigborhoods In {{ city_name.title }}</h6>
                     
                    {% endif %}

      
                    <ul class="sidebar-card-list">
                      {% if neigborhood_name %}
                        {% for neigborhood in neigborhood_name %}
                          {% if neigborhood.num_property > 0 %}
                            <li><a href="{{ neigborhood.get_neighborhood_url }}"><i class="mdi mdi-chevron-right"></i> {{neigborhood.title}}<span class="sidebar-badge">{{ neigborhood.num_property }} </span></a></li>
                          {% endif %}
                        {% endfor %}   
                      {% endif %}
                    </ul>
      
      
                  </div>
                </div>
      
                {% if featured %}
                
                  <div class="card">
        
                    <div class="card-body">
                      <h5 class="card-title mb-4">Featured Properties</h5>
                      
                      <div id="featured-properties" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for featured in featured|slice:":3" %}
                              <li data-target="#featured-properties" data-slide-to="{{ featured.count }}" class="{% if forloop.counter == 1 %}active{% endif %}"></li>
                          <!-- <li data-target="#featured-properties" data-slide-to="1"></li> -->
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">
                          {% for featured in featured|slice:":3" %}
                            <div class="{% if forloop.counter == 1 %}carousel-item active{% else %} carousel-item{% endif %}">

                              {% include 'property/snippet/featured_card_small.html' with instance=featured %}
                                  
                              
                            </div>
                          {% endfor %}
                          
                        </div>
                      </div>
        
                    </div>
                  </div>

        
                </div>
              {% endif %}
      
              <div class="col-lg-9 col-md-9">
      
      
      
                <!-- <div class="osahan_top_filter row">
                  <div class="col-lg-6 col-md-6 tags-action">
                   
                  </div>
                  <div class="col-lg-6 col-md-6 sort-by-btn float-right">
                    
                    <div class="dropdown float-right">
                      <button class="btn btn-success btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="mdi mdi-filter"></i> Sort by
                      </button>
                      <div class="dropdown-menu float-right" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#"><i class="mdi mdi-chevron-right"></i> New </a>
                        <a class="dropdown-item" href="#"><i class="mdi mdi-chevron-right"></i> Price: Low to High </a>
                        <a class="dropdown-item" href="#"><i class="mdi mdi-chevron-right"></i> Price: High to Low </a>
                      </div>
                    </div>
                  </div>
                </div> -->
      
      
                  <div class="row">
                      {% for obj in city_property %}
                                  
                          {% include 'property/snippet/property_card_smaller.html' with instance=obj %}
                                  

                      {% endfor %}
                  </div>
      
                  {% include 'property/snippet/paginator.html' with paginate=city_property %}
      
              </div>
            </div>
          </div>
        </section>
        <!-- End Properties List -->


      
    <!-- END: slider  -->

  {% else %}

  <section class="section-padding">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-md-8">
                  <h5>Ops No property here </h5>
      
              <div class="card">
              </div>
          </div>
      </div>
  </section>

  {% endif %}

         
    {% endblock %}

property/templates/property/property_list_snippet.html
<div class="container">
    {% for instance in property_list %}
    <div class="col-md-4">
        <div class="thumbnail">
            {% if instance.main_image %}
                <a href="{{ instance.get_absolute_url }}" >
                <img src="{{instance.main_image.url}}" alt="{{ instance.title }} logo">
                </a>
            {% endif %}
            <div class="caption">
                <h3>{{instance.title}}</h3>
                <p>{{ instance.description| truncatewords:10}}</p>
                <p><a href="{{ instance.get_absolute_url }}" class="btn btn-primary" role="button">View</a> 
                
                    
            </div>
        </div>
        
    </div>
       
    {% endfor %}
    
  </div>

property/templates/property/property_neighborhood_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block style %}
    <link href='{% static "css/property_list.css" %}' rel="stylesheet">
{% endblock %}




   {% block content %}

    <!-- Main Slider With Form -->
    <section class="osahan-slider">
            <div id="osahanslider" class="carousel slide" data-ride="carousel">
            
                    <div class="carousel-inner" role="listbox">
                        {% if city %}
                       
                            <div class="carousel-item active" 
                                style="background-image: {% if city.image %}url('{{ city.image.url }}') {% else %} url({% static 'images/city_view.jpg' %}){% endif %}">      
                                <div class="overlay"></div>
                            </div>
                         
                        {% endif %}
                       
                    </div>
                    
                </div>
        
        {% include 'search/snippet/search_form.html' %}
    </section>
         <!-- End Main Slider With Form -->


         
    <!-- END: header -->

    {% if neighborhood_property %}


            <!-- Properties List -->
        <section class="section-padding">
                <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3">
            
                    <div class="card">
            
                        <div class="card-body">
                        <h6 class="card-title mb-3">Property Type</h6>
            
                        <ul class="sidebar-card-list">
                            {% if property_type %}
                                {% for type in property_type %}
                                    <li><a href="#"><i class="mdi mdi-chevron-right"></i> For {{ type.title }} <span class="sidebar-badge"></span></a></li>
                                    <!-- <li><a href="#"><i class="mdi mdi-chevron-right"></i> For Sale <span class="sidebar-badge">1200</span></a></li> -->
                                {% endfor %}
                            {% endif %}
                        </ul>
            
            
                        </div>
                    </div>
            
            
                    <div class="card">
            
                        <div class="card-body">
                            {% if neigborhood_name %}
                                    <h6 class="card-title mb-3">Close to {{ neigborhood_name.title }}</h6>
                            {% endif %}

            
                        <ul class="sidebar-card-list">
                            {% if city_neigborhoods %}
                                {% for neigborhood in city_neigborhoods %}
                                    <li><a href="{{ neigborhood.get_neighborhood_url }}"><i class="mdi mdi-chevron-right"></i> {{neigborhood.title }}<span class="sidebar-badge">{{ neigborhood.num_property }}</span></a></li>
                                    
                                {% endfor %}   
                            {% endif %}
                        </ul>
            
            
                        </div>
                    </div>
            
                    {% if featured %}
                    
                        <div class="card">
            
                        <div class="card-body">
                            <h5 class="card-title mb-4">Featured Properties</h5>
                            
                            <div id="featured-properties" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for featured in featured|slice:":3" %}
                                    <li data-target="#featured-properties" data-slide-to="{{ featured.count }}" class="{% if forloop.counter == 1 %}active{% endif %}"></li>
                                <!-- <li data-target="#featured-properties" data-slide-to="1"></li> -->
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                {% for featured in featured|slice:":3" %}
                                <div class="{% if forloop.counter == 1 %}carousel-item active{% else %} carousel-item{% endif %}">

                                    {% include 'property/snippet/featured_card_small.html' with instance=featured %}
                                        
                                    
                                </div>
                                {% endfor %}
                                
                            </div>
                            </div>
            
                        </div>
                        </div>

            
                    </div>
                    {% endif %}
            
                    <div class="col-lg-9 col-md-9">
            
            
            
                    <!-- <div class="osahan_top_filter row">
                        <div class="col-lg-6 col-md-6 tags-action">
                        
                        </div>
                        <div class="col-lg-6 col-md-6 sort-by-btn float-right">
                       
                        <div class="dropdown float-right">
                            <button class="btn btn-success btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-filter"></i> Sort by
                            </button>
                            <div class="dropdown-menu float-right" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#"><i class="mdi mdi-chevron-right"></i> New </a>
                            <a class="dropdown-item" href="#"><i class="mdi mdi-chevron-right"></i> Price: Low to High </a>
                            <a class="dropdown-item" href="#"><i class="mdi mdi-chevron-right"></i> Price: High to Low </a>
                            </div>
                        </div>
                        </div>
                    </div> -->
            
            
                        <div class="row">
                            {% for obj in neighborhood_property %}
                                        
                                {% include 'property/snippet/property_card_smaller.html' with instance=obj %}
                                        

                            {% endfor %}
                        </div>
            
                        {% include 'property/snippet/paginator.html' with paginate=neighborhood_property %}
            
                    </div>
                </div>
                </div>
            </section>
            <!-- End Properties List -->


            
        <!-- END: slider  -->
    {% else %}

    <section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <h5>No property here </h5>
        
                <div class="card">
                </div>
            </div>
        </div>
    </section>

    {% endif %}

         
    {% endblock %}