main/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from .import views
from django.contrib.auth.views import login,logout
# from main.views import IndexView, LoginView
from main.views import MainView, LoginView

from django.contrib.auth.views import(
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    LogoutView,

    
)

from property.views import UserFavoriteProperty
from .views import ContactView, AboutView



app_name = 'main'




urlpatterns = [
    url(r'^$', MainView.as_view(), name='index'),
    
    # url(r'^login/$',login,{'template_name':'main/login.html'},name='login'),
    
    url(r'^contact/$',ContactView.as_view(),name='contact'),
    url(r'^about/$',AboutView.as_view(),name='about'),

    url(r'^login/$',LoginView.as_view(),name='login'),

    # url(r'^login/$',views.login_page,name='login'),

    # url(r'^logout/$',logout,{'template_name':'main/index.html'},name='logout'),

    url(r'^logout/$',LogoutView.as_view(),name='logout'),

    url(r'^register/$', views.register, name='register'),

    url(r'^change-password/$',views.change_password, name="change_password"),
   
    url(r'^profile/$',views.user_profile, name="profile"),
    
    url(r'^reset-password/$', password_reset, {'template_name':'main/reset_password.html',
                                                    'email_template_name':'main/reset_password_email.html',
                                                    'post_reset_redirect':'main:password_reset_done',
                                                    'from_email':'main@django.com',},name='password_reset'),

   
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'main/reset_password_done.html'},
                                                         name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':'main/reset_password_confirm.html',
                              'post_reset_redirect': reverse_lazy('main:password_reset_complete')},
                              name='password_reset_confirm'),

    url(r'reset-password/complete/$', password_reset_complete,{'template_name':'main/reset_password_complete.html'}, name='password_reset_complete'),

    url(r'^favorite/$',UserFavoriteProperty.as_view(),name='favorite'),

]



real/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',  include('main.urls',namespace='main')),
    url(r'^property/', include('property.urls',namespace='property')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^tag/', include("tag.urls", namespace='tag')),
    url(r'^realtor/', include("realtor.urls", namespace='realtor')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realtor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from property.views import PropertyCreateView
from property.views import RealtorPropertyListView
from property.views import PropertyUpdateView #PropertyOtherImages
from .import views


from .views import (
        RealtorView,
        RealtorDetailRedirectView,
        # Realtor_Profile,
        RealtorUpdate,
        RealtorsListView,
        RealtorsDetailView,
        RealtorCreate

        
        )

urlpatterns = [ 
    url(r'^$', RealtorView.as_view(), name='home'),
    url(r'^create/$', RealtorCreate.as_view(), name='create_reator'),
    url(r'^update/(?P<pk>\d+)/$', RealtorUpdate.as_view(), name='update'),
    url(r'^property/$',RealtorPropertyListView.as_view(),name='property_list'),
    url(r'^property/create/$',PropertyCreateView.as_view(),name='create'),
    # url(r'^property/add-more-images/$',PropertyOtherImages.as_view(),name='add_more_images'),
    url(r'^property/(?P<pk>\d+)/edit/$',PropertyUpdateView.as_view(),name='property_edit'),
    url(r'^property/(?P<pk>\d+)/$',RealtorDetailRedirectView.as_view()),
    url(r'^realtors/$', RealtorsListView.as_view(), name='realtors'),
    url(r'^realtors/(?P<pk>\d+)/$', RealtorsDetailView.as_view(), name='realtor-detail'),
   # url(r'^realtor_profile/(?P<pk>\d+)/$', Realtor_Profile.as_view(), name='realtor_profile')
    # url(r'^realtor_profile/$', views.realtor_profile, name='realtor_profile')
] 

tag/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagDetailView,
        TagListView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
] 

templates/Untitled-1.html
<header>
         <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
               <a class="navbar-brand text-success logo" href="/"><i class="mdi mdi-home-map-marker"></i> <strong>Hommie</strong></a>
               <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarResponsive">
                  <ul class="navbar-nav mr-auto mt-2 mt-lg-0 margin-auto">
                     <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        HOME
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownPortfolio">
                           <a class="dropdown-item" href="index1.html">Home With Search</a>
                           <a class="dropdown-item" href="index2.html">Home With Map</a>
                           <a class="dropdown-item" href="index3.html">Home With Property Info</a>
                        </div>
                     </li> -->
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'property:list' %}" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Properties
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownPortfolio">
                           <a class="dropdown-item" href="properties-grid.html">Properties Grid</a>
                           <a class="dropdown-item" href="properties-list.html">Properties List</a>
                           <a class="dropdown-item" href="property-single-slider.html">Property Single Slider</a>
                           <a class="dropdown-item" href="property-single-gallery.html">Property Single Gallery</a>
                        </div>
                     </li>
                     <li>
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Realtor
                        </a>
            
                     </li>
                     <li>
                         <a>
                             Kola
                         </a>
                     </li>

                    <li>
                        <a href="#" aria-haspopup="true" aria-expanded="false">
                        About Us
                        </a>
                     </li>

                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Contact
                        </a>
                     </li>

                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hi {{request.user.first_name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownPortfolio">
                            <a class="dropdown-item" href="user-profile.html">User Profile</a>
                            <a class="dropdown-item" href="social-profiles.html">Social Profiles</a>
                            <a class="dropdown-item" href="my-properties.html">My Properties</a>
                            <a class="dropdown-item" href="favorite-properties.html">Favorite Properties</a>
                            <a class="dropdown-item" href="add-property.html">Add Property</a>
                            </div>
                        </li>
                     </ul>
                    {% else %}
                     
                 

                        <div class="my-2 my-lg-0">
                            <ul class="list-inline main-nav-right">
                                <li class="list-inline-item">
                                <a class="btn btn-link btn-sm" href="login.html">Sign In</a>
                                </li>
                                <li class="list-inline-item">
                                <a class="btn btn-success btn-sm" href="register.html">Sign Up</a>
                                </li>
                            </ul>
                        </div>
                    {% endif %}
               </div>
            </div>
         </nav>
      </header>
      <!-- End Navbar -->

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{% block title %}MyHommes {% endblock %}</title>
        {% load staticfiles %}


       
        {% include 'base/css.html' %}
        
       
        {% include 'base/js.html' %}

        {% block style %}{% endblock %}
         

    </head>

    <body>
        
       <!-- START: header -->
  
  <div class="probootstrap-loader"></div>

  
  <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">
            <a class="navbar-brand text-success logo" href="/"><i class="mdi mdi-home-map-marker"></i> <strong>MyHommes</strong></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav mr-auto mt-2 mt-lg-0 margin-auto">
                  
                  <li class="nav-item dropdown">
                    
                     <a class="nav-link" href="{% url 'property:list' %}">
                        Properties
                     </a>
                    
                  </li>
                  <li>
                     <a class="nav-link" href="{% url 'realtor:realtors' %}" >
                     Realtor
                     </a>
         
                  </li>

                 <li class="nav-item dropdown">
                     <a class="nav-link" href="{% url 'main:about' %}" >
                     About Us
                     </a>
                  </li>

                  <li>
                     <a class="nav-link" href="{% url 'main:contact' %}">
                     Contact
                     </a>
                  </li>

                 {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Hi {{request.user.first_name }}
                         </a>
                         <div class="dropdown-menu" aria-labelledby="navbarDropdownPortfolio">
                        
                          <a class="dropdown-item" href="{% url 'main:profile' %}">User Profile</a>
                          {% if request.user.realtor %}
                            <a class="dropdown-item" href="{% url 'realtor:create' %}">Add Property</a>
                            <a class="dropdown-item" href="{% url 'realtor:home' %}">My Properties</a>
                          {% endif %}
                          <a class="dropdown-item" href="#">Favorite Properties</a>
                          <a class="dropdown-item" href="{% url 'main:change_password' %}">Change Password</a>
                          <a class="dropdown-item" href="{% url 'main:logout' %}">logout</a>
                          
                        
                         </div>
                    </li>
             
                 {% else %}

                   </ul>
              

                     <div class="my-2 my-lg-0">
                         <ul class="list-inline main-nav-right">
                             <li class="list-inline-item">
                             <a class="btn btn-link btn-sm" href="{% url 'main:login' %}">Sign In</a>
                             </li>
                             <li class="list-inline-item">
                             <a class="btn btn-success btn-sm" href="{% url 'main:register' %}">Sign Up</a>
                             </li>
                         </ul>
                     </div>
                 {% endif %}
                    </ul>
                 <div class="my-2 my-lg-0">
                    <ul class="list-inline main-nav-right">
                        {% if request.user.realtor %}
                            <li class="list-inline-item">
                                <a class="btn btn-link btn-sm" href="{% url 'realtor:create' %}">Create Property</a>
                            </li>
                        {% else %}
                            {% if user.is_authenticated %}
                                <li class="list-inline-item">
                                    <a class="btn btn-link btn-sm" href="{% url 'realtor:create_reator' %}">Become a Realtor</a>
                                </li>
                            {% else %}
                                <li class="list-inline-item">
                                    <a class="btn btn-link btn-sm" href="{% url 'main:register' %} ">Become a Realtor</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    </ul>
                </div>
                

            </div>
         </div>
      </nav>
   </header>
   <!-- End Navbar -->

  

            <div>
                {% block content %}
                {% endblock %}
            </div>

            <!-- Footer -->
      <section class="section-padding footer bg-white">
          <div class="container">
             <div class="row">
                <div class="col-lg-4 col-md-3">
                   <h4 class="mb-5"><a class="text-success logo" href="/"><i class="mdi mdi-home-map-marker"></i> <strong>MyHommes</strong></a></h4>
                   <p>House 1, 21 road<br>Efab estate, LifeCamp Abuja</p>
                   <p class="mb-0"><a class="text-dark" href="#">+2348162269572</a></p>
                   <p class="mb-0"><a class="text-success" href="#">kolajubril@gmail.com</a></p>
                   <p class="mb-0"><a class="text-info" href="#">www.hommie.com</a></p>
                </div>
                <div class="col-lg-2 col-md-2">
                   <h6 class="mb-4">COMPANY</h6>
                   <ul>
                   <li><a href="#">About us</a></li>
                   <li><a href="#">Career</a></li>
                   <li><a href="#">Services</a></li>
                   <li><a href="#">Properties</a></li>
                   <li><a href="#">Contact</a></li>
                   <ul>
                </div>
                <div class="col-lg-2 col-md-2">
                   <h6 class="mb-4">LEARN MORE</h6>
                   <ul>
                   <li><a href="#">Privacy</a></li>
                   <li><a href="#">Terms & Conditions</a></li>
                   <li><a href="#">Account</a></li>
                   <li><a href="#">FAQ</a></li>
                   <li><a href="#">Blog</a></li>
                   <ul>
                </div>
                <div class="col-lg-4 col-md-4">
                   <h6 class="mb-4">NEWSLETTER</h6>
                   <div class="input-group">
                      <input type="text" class="form-control" placeholder="Email Address..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                      <div class="input-group-append">
                         <button class="btn btn-outline-secondary" type="button"><i class="mdi mdi-arrow-right"></i></button>
                      </div>
                   </div>
                   <h6 class="mb-4 mt-5">GET IN TOUCH</h6>
                   <div class="footer-social">
                      <a href="#"><i class="mdi mdi-facebook"></i></a>
                      <a href="#"><i class="mdi mdi-twitter"></i></a>
                      <a href="#"><i class="mdi mdi-instagram"></i></a>
                      <a href="#"><i class="mdi mdi-google"></i></a>
                   </div>
                </div>
             </div>
          </div>
       </section>
       <!-- End Footer -->
       <!-- Copyright -->
       <section class="pt-4 pb-4 text-center">
          <p class="mt-0 mb-0">© Copyright 2018 MyHommes. All Rights Reserved</p>
          <small class="mt-0 mb-0">
          Made with <i class="mdi mdi-heart text-danger"></i>	by 
          <a class="text-dark" target="_blank" href="http://www.kolaemiola.xyz">Kola Emiola</a>
          </small>
          <br/>
          <small class="mt-0 mb-0">
            Bootstrap Themes by
            <a class="text-dark" target="_blank" href="https://askbootstrap.com/">Ask Bootstrap</a>
          </small>
       </section>
       <!-- End Copyright -->

             
            
    
    </body>
</html>