main/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from .import views
from django.contrib.auth.views import login,logout
# from main.views import IndexView, LoginView
from main.views import MainView, LoginView

from django.contrib.auth.views import(
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    LogoutView,

    
)

from property.views import UserFavoriteProperty
from .views import ContactView, AboutView



app_name = 'main'




urlpatterns = [
    url(r'^$', MainView.as_view(), name='index'),
    
    # url(r'^login/$',login,{'template_name':'main/login.html'},name='login'),
    
    url(r'^contact/$',ContactView.as_view(),name='contact'),
    url(r'^about/$',AboutView.as_view(),name='about'),

    url(r'^login/$',LoginView.as_view(),name='login'),

    # url(r'^login/$',views.login_page,name='login'),

    # url(r'^logout/$',logout,{'template_name':'main/index.html'},name='logout'),

    url(r'^logout/$',LogoutView.as_view(),name='logout'),

    url(r'^register/$', views.register, name='register'),

    url(r'^change-password/$',views.change_password, name="change_password"),
   
    url(r'^profile/$',views.user_profile, name="profile"),
    
    url(r'^reset-password/$', password_reset, {'template_name':'main/reset_password.html',
                                                    'email_template_name':'main/reset_password_email.html',
                                                    'post_reset_redirect':'main:password_reset_done',
                                                    'from_email':'main@django.com',},name='password_reset'),

   
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'main/reset_password_done.html'},
                                                         name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':'main/reset_password_confirm.html',
                              'post_reset_redirect': reverse_lazy('main:password_reset_complete')},
                              name='password_reset_confirm'),

    url(r'reset-password/complete/$', password_reset_complete,{'template_name':'main/reset_password_complete.html'}, name='password_reset_complete'),

    url(r'^favorite/$',UserFavoriteProperty.as_view(),name='favorite'),

]



real/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',  include('main.urls',namespace='main')),
    url(r'^property/', include('property.urls',namespace='property')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^tag/', include("tag.urls", namespace='tag')),
    url(r'^realtor/', include("realtor.urls", namespace='realtor')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realtor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from property.views import PropertyCreateView
from property.views import RealtorPropertyListView
from property.views import PropertyUpdateView #PropertyOtherImages
from .import views


from .views import (
        RealtorView,
        RealtorDetailRedirectView,
        # Realtor_Profile,
        RealtorUpdate,
        RealtorsListView,
        RealtorsDetailView,
        RealtorCreate

        
        )

urlpatterns = [ 
    url(r'^$', RealtorView.as_view(), name='home'),
    url(r'^create/$', RealtorCreate.as_view(), name='create_reator'),
    url(r'^update/(?P<pk>\d+)/$', RealtorUpdate.as_view(), name='update'),
    url(r'^property/$',RealtorPropertyListView.as_view(),name='property_list'),
    url(r'^property/create/$',PropertyCreateView.as_view(),name='create'),
    # url(r'^property/add-more-images/$',PropertyOtherImages.as_view(),name='add_more_images'),
    url(r'^property/(?P<pk>\d+)/edit/$',PropertyUpdateView.as_view(),name='property_edit'),
    url(r'^property/(?P<pk>\d+)/$',RealtorDetailRedirectView.as_view()),
    url(r'^realtors/$', RealtorsListView.as_view(), name='realtors'),
    url(r'^realtors/(?P<pk>\d+)/$', RealtorsDetailView.as_view(), name='realtor-detail'),
   # url(r'^realtor_profile/(?P<pk>\d+)/$', Realtor_Profile.as_view(), name='realtor_profile')
    # url(r'^realtor_profile/$', views.realtor_profile, name='realtor_profile')
] 

tag/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagDetailView,
        TagListView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
] 

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save


# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The given must be email')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    # User Model


class User(AbstractUser):
    # description = models.CharField(max_length=200, default='')
    # city = models.CharField( max_length=200,default='')

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    address = models.CharField(blank=True, max_length=200)
    city = models.CharField(blank=True, max_length=200)
    state = models.CharField(blank=True, max_length=200)
    phone_number = models.IntegerField(blank=True, default='0')

    def __str__(self):
        return self.user.email


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile, User
from django.contrib.auth import get_user_model



User = get_user_model()


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None


    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    # save user method
    def save(self, commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']    

        if commit:
            user.save()

        return user 

class UpdateCustomerForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


class UpdateCustomerFormTwo(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields =(
            'address',
            'city',
            'state',
            'phone_number'
        )

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

main/views.py
from django.shortcuts import render
from django.utils.http import is_safe_url
from django.views.generic import TemplateView, CreateView, FormView
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.db.models import Count
from .models import User

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from .forms import RegistrationForm, UpdateCustomerForm, UpdateCustomerFormTwo, LoginForm
from .signals import user_logged_in
from .mixins import LoginRequiredMixin
import random

from django.views.generic import View
from django.shortcuts import render

# Create your views here.

from property.models import Property, City
from random import shuffle
import random


# Create your views here.

# class IndexView(TemplateView):
#     template_name = 'main/index.html'


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)  # from our registration form class in form.py, we get the request method

        if form.is_valid():
            form.save()

            email = request.POST.get('email')
            password = request.POST.get('password1')

            user = authenticate(
                request,
                email=email,
                password=password
            )
            login(request, user)
            return redirect(reverse('main:index'))
    else:
        form = RegistrationForm()
    args = {'form': form}
    return render(request, 'main/reg_form.html', args)


def user_profile(request):
    if request.method == "POST":
        form = UpdateCustomerForm(request.POST, instance=request.user, prefix='form')
        form2 = UpdateCustomerFormTwo(request.POST, instance=request.user.userprofile, prefix='form2')

        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return redirect(reverse('main:profile'))
        else:
            return render(request, 'main/profile.html', {'form': form, 'form2': form2})
    else:
        form = UpdateCustomerForm(instance=request.user, prefix='form')
        form2 = UpdateCustomerFormTwo(instance=request.user.userprofile, prefix='form2')
        args = {'form': form, 'form2': form2}
        return render(request, 'main/profile.html', args)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Your new password has been saved")
            update_session_auth_hash(request, form.user)
            return redirect(reverse('main:profile'))

    else:
        form = PasswordChangeForm(user=request.user)
    args = {'form': form}
    return render(request, 'main/change_password.html', args)


# def login_page(request):
#     form = LoginForm(request.POST or None)
#     context = {
#         "form": form
#     }

#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         print(form.cleaned_data)
#         email  = form.cleaned_data.get("email")
#         password  = form.cleaned_data.get("password")
#         user = authenticate(request, email=email, password=password)
#         if user is not None:

#             login(request, user)

#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect("/")

#         else:
#             # Return an 'invalid login' error message.
#             print("Error")

#     return render(request, "main/login.html", context)

class LoginView(FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'main/login.html'

    def form_valid(self, form):
        request = self.request
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            user_logged_in.send(user.__class__, instance=user, request=request)
            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                return redirect("/")
        return super(LoginView, self).form_invalid(form)


class MainView(View):
    template_name = 'main/index.html'

    def get(self, request, *args, **kwargs):
        tag_views = None
        property = None
        top_tags = None
        try:
            tag_views = request.user.tagview_set.all().order_by("-count")[:5]
        except:
            pass

        owned = None

        try:
            owned = request.user.myproperty.property.all()
        except:
            pass

        if tag_views:
            top_tags = [x.tag for x in tag_views]
            property = Property.objects.filter(tag__in=top_tags)
            if owned:
                property = property.exclude(pk__in=owned)

            if property.count() < 10:
                property = Property.objects.all().order_by("?")
                if owned:
                    property = Property.exclude(pk__in=owned)
                property = property[:10]
            else:
                property = property.distinct()
                property = sorted(property, key=lambda x: random.random())

        featured_property = list(Property.objects.filter(featured = True))
        shuffle(featured_property)
        # city          = City.objects.filter(slug__in = ["abuja" , "lagos" , "ibadan" , "calabar" , "kano","port-harcourt"]).order_by("id")
        featured_cities          = City.objects.filter(slug__in = ["abuja" , "lagos" , "ibadan" , "calabar" , "kano","port-harcourt"]).annotate(num_property = Count("property")).order_by("-num_property")

        cities = City.objects.all().annotate(num_property = Count("property")).order_by("-num_property")

        context = {
            "property": property,
            "top_tags": top_tags,
            "featured_property":featured_property,
            "featured_cities":featured_cities,
            "cities" : cities
        }
        return render(request, "main/index.html", context)

class ContactView(TemplateView):
    template_name = 'main/contact.html'

class AboutView(TemplateView):
    template_name = 'main/about.html'

main/templates/main/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}



<!-- Main Slider With Form -->
<section class="osahan-slider">
    <div id="osahanslider" class="carousel slide" data-ride="carousel">
       <ol class="carousel-indicators">
          <li data-target="#osahanslider" data-slide-to="0" class="active"></li>
          <li data-target="#osahanslider" data-slide-to="1"></li>
          <li data-target="#osahanslider" data-slide-to="2"></li>
       </ol>
       <div class="carousel-inner" role="listbox">
          <div class="carousel-item active" style="background-image: url({% static 'images/2.jpg' %});"><div class="overlay"></div></div>
          <div class="carousel-item" style="background-image: url({% static 'images/1.jpg' %});"><div class="overlay"></div></div>
          <div class="carousel-item" style="background-image: url({% static 'images/3.jpg' %});" ><div class="overlay"></div></div>
       </div>
       <a class="carousel-control-prev" href="#osahanslider" role="button" data-slide="prev">
       <span class="carousel-control-prev-icon" aria-hidden="true"></span>
       <span class="sr-only">Previous</span>
       </a>
       <a class="carousel-control-next" href="#osahanslider" role="button" data-slide="next">
       <span class="carousel-control-next-icon" aria-hidden="true"></span>
       <span class="sr-only">Next</span>
       </a>
    </div>
    {% include 'search/snippet/search_form.html' %}
 </section>
 <!-- End Main Slider With Form -->
 <!-- Properties List -->
 <section class="section-padding">
    <div class="section-title text-center mb-5">
       <h2>Latest Properties</h2>
       <p>.</p>
    </div>
    <div class="container">
       <div class="row">

            {% if featured_property %}
            
                  {% for property in featured_property|slice:":6"  %}
                  
                        {% include 'property/snippet/property_card.html' with instance=property %}


                  {% endfor %}
            {% endif %}
          
          
       </div>
    </div>
    <div class="row mt-4">
            <div class="col-md-12 text-center">
               <a class="btn btn-success" href="{% url 'property:list' %}">VIEW ALL</a>
            </div>
      </div>
 </section>
 <!-- End Properties List -->
 <!-- Properties by City -->
 <section class="section-padding bg-white">
    <div class="section-title text-center mb-5">
       <h2>Top Cities</h2>
       <p>We bring you the best properties in your favorite city.</p>
    </div>
    <div class="container">
            <div class="row">
                  {% if featured_cities %}
            
                        {% for c in featured_cities %}
                        
                              {% include 'main/snippet/featured_city_card.html' with instance=c %}
      
      
                        {% endfor %}
                  {% endif %}
            
            </div>
    
    </div>
   
 </section>

 <section class="section-padding bg-white">
      <div class="section-title text-center mb-5">
         <h2>Property By Cities</h2>
         <!-- <p>List of Properties in your favorite city.</p> -->
      </div>
      <div class="container">
              <div class="row">
                    {% if cities %}
              
                          {% for city in cities %}
                          
                                {% include 'main/snippet/city_card.html' with instance=city %}
        
        
                          {% endfor %}
                    {% endif %}
              
              </div>
      
      </div>
   </section>

 <!-- End Blog -->
 <!-- Join Team -->
 <section class="section-padding bg-dark text-center">
    <h2 class="text-white mt-0">Join our professional team & agents<br>to start selling your house</h2>
    <p class="text-white mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    <button type="button" class="btn btn-success">Contact Us</button> <button type="button" class="btn btn-outline-success">Read More</button>
 </section>
 <!-- End Join Team -->

{% endblock %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}   



 <!-- Login -->
 <section class="section-padding">
        <div class="container">
   <div class="row">
       <div class="col-lg-5 col-md-5 mx-auto">
       <div class="card padding-card">
         <div class="card-body">
         <h5 class="card-title mb-4">Login</h5>
           <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
             <button type="submit" class="btn btn-success btn-block">SIGN IN</button>
           </form>
           <div class="mt-4 text-center login-with-social">
           <a href="{% url 'main:register' %}"><button type="button" class="btn btn-default btn-block">SIGN UP</button></a> <br />
           <button type="button" class="btn btn-facebook btn-block"><i class="mdi mdi-facebook"></i> Login With Facebook</button>
           <button type="button" class="btn btn-twitter btn-block"><i class="mdi mdi-twitter"></i> Login With Twitter</button>
           <button type="button" class="btn btn-google btn-block"><i class="mdi mdi-google-plus"></i> Login With Google</button>
           </div>
           <div class="mt-4 text-center">
           <a href="{% url 'main:password_reset' %}">Forget your password?</a>
           </div>
         </div>
       </div>
       </div>
   </div>
</div>

 

{% endblock %}   

main/templates/main/logout.html
{% extends 'base.html' %}
 {% load staticfiles %}

{% block content %}
    <div class="container">
        <h2>You have logged out</h2>
    </div>

{% endblock %}

main/templates/main/profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

   {% block content %}  

    {% if request.user.realtor %}
        {% if request.user.realtor.image %}
            <section class="section-padding bg-dark inner-header" style="background-image:  url('{{ request.user.realtor.image.url }}')" >
        {% endif %}
   {% else %}
        {% if request.user.image %}
            <section class="section-padding bg-dark inner-header" style="background-image:  url('{{ request.user.image.url }}')" >
        {% endif %}
    {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1 class="mt-0 mb-3 text-white">User Profile</h1>
                    <div class="breadcrumbs">
                        <p class="mb-0 text-white"><a class="text-white" href="#">Home</a>  /  <span class="text-success">User Profile</span></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Inner Header -->



    <section class="tab-view">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                    <ul class="nav justify-content-center">
                     
                    
                            <li class="nav-item">
                                <a class="nav-link active text-success" href="{% url 'main:profile' %}">User Profile</a>
                            </li>
                            {% if request.user.realtor %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'realtor:update' pk=request.user.realtor.id %}">Edit Realtor Information</a>
                                </li>
                            {% endif %}
                            {% if request.user.realtor %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'realtor:home' %}">My Properties</a>
                                </li>
                            {% endif %}
                            
                            
        
                            <li class="nav-item">
                                <a class="nav-link" href="favorite-properties.html">Favorite Properties</a>
                            </li>
                            {% if request.user.realtor %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'realtor:create' %}">Add Property</a>
                                </li>
                            {% endif %}
                    
                    </ul>
                    </div>
                </div>
            </div>
    </section>

<section class="section-padding">
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8 mx-auto">
            <form method="post">
                <div class="card padding-card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">{{ request.user.first_name }} Details</h5>

                        <!-- <div class="form-group">
                            <label>First Name <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" placeholder="Enter First Name">
                        </div>
                        <div class="form-group">
                            <label>Last Name <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" placeholder="Enter Last Name">
                        </div>
                        <div class="form-group">
                            <label>Email Address <span class="text-danger">*</span></label>
                            <input type="email" class="form-control" placeholder="Enter Email Address">
                        </div>
                        <div class="form-group">
                            <label>Phone <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" placeholder="Enter Phone">
                        </div>
                        <div class="form-group">
                            <label>Location <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" placeholder="Enter Locations">
                        </div>
                        <div class="form-group">
                            <label>About Me <span class="text-danger">*</span></label>
                            <textarea rows="10" cols="100" class="form-control"></textarea>
                        </div> -->
                        {% csrf_token %}
                        {{ form|crispy }}
                        <br/>
                        {{request.user.email}}
                        <br/>
                        <br/>
                        <br/>
                    </div>
                </div>
                <div class="card padding-card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">More details</h5>

                        <!-- <div class="form-group">
                            <label>Password <span class="text-danger">*</span></label>
                            <input type="password" class="form-control" placeholder="">
                        </div>
                        <div class="form-group">
                            <label>Confirm Password <span class="text-danger">*</span></label>
                            <input type="password" class="form-control" placeholder="">
                        </div> -->

                        {{ form2|crispy }}
                    </div>
                </div>


                <button type="submit" class="btn btn-success">SAVE EDITS</button>
            </form>
        </div>
    </div>
</div>
</section>
     <!-- End User Profile -->

{% endblock %}
  

main/templates/main/reg_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
    <link rel="stylesheet" href='{% static "css/register.css" %}'>
{% endblock %}


{% block content %}   




 <!-- Register -->
 <section class="section-padding">
        <div class="container">
          <div class="row">
              <div class="col-lg-5 col-md-5 mx-auto">
              <div class="card padding-card">
                <div class="card-body">
                <h5 class="card-title mb-4">Register</h5>
                  <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                    <button type="submit" class="btn btn-success btn-block">REGISTER</button>
                  </form>
                  <div class="mt-4 text-center login-with-social">
                  <a href="{% url 'main:login' %} "><button type="button" class="btn btn-default btn-block">Sign In</button></a><br />
                  <button type="button" class="btn btn-facebook btn-block"><i class="mdi mdi-facebook"></i> Login With Facebook</button>
                  <button type="button" class="btn btn-twitter btn-block"><i class="mdi mdi-twitter"></i> Login With Twitter</button>
                  <button type="button" class="btn btn-google btn-block"><i class="mdi mdi-google-plus"></i> Login With Google</button>
                  </div>
                </div>
              </div>
              </div>
          </div>
        </div>
      
    </section>
            <!-- End Register -->


{% endblock %}     

main/templates/main/reset_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}


<section class="section-padding">
        <div class="container">
   <div class="row">
       <div class="col-lg-5 col-md-5 mx-auto">
       <div class="card padding-card">
         <div class="card-body">
         <h5 class="card-title mb-4">Reset Password</h5>
           <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
             <button type="submit" class="btn btn-success btn-block">RESET PASSWORD</button>
           </form>
           
           <div class="mt-4 text-center">
            Don't have an account? <a href="{% url 'main:register' %}">Register</a>
           </div>
         </div>
       </div>
       </div>
   </div>
</div>
</section>

{% endblock %}

main/templates/main/reset_password_complete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}



<section class="section-padding">
    <div class="container">
<div class="row">
   <div class="col-lg-5 col-md-5 mx-auto">
   <div class="card padding-card">
     <div class="card-body">
     <h5 class="card-title mb-4">Password reset complete </h5>
     <p>
        You can now login 
      </p>
      <a href="{% url 'main:login' %}">login</a>

     </div>
   </div>
   </div>
</div>
</div>
</section>
{% endblock %}

main/templates/main/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'main:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
	
{% trans "Thanks for using our site!" %}
	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}